# Generated by Django 5.0.2 on 2024-03-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.budgets')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_operation', models.DateField()),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_currency', models.CharField(max_length=3)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('cashback', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('mcc', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField()),
                ('bonuses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rounding_for_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_amount_rounded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_category', models.CharField(blank=True, max_length=100, null=True)),
                ('original_category', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('date_of_operation', 'operation_amount')},
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name_in_report', models.CharField(blank=True, max_length=100, null=True)),
                ('descr_in_report', models.CharField(blank=True, max_length=100, null=True)),
                ('mcc_in_report', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.categories')),
            ],
            options={
                'unique_together': {('cat_name_in_report', 'descr_in_report', 'mcc_in_report')},
            },
        ),
    ]
